plugins:
  # Enable XML formatting plugin
  - "@prettier/plugin-xml"
  # Enable JSON sorting plugin
  - prettier-plugin-sort-json
  # Enable package.json sorting plugin
  - prettier-plugin-packagejson

# Sort JSON recursively
jsonRecursiveSort: true

# Format whitespaces in XML
xmlWhitespaceSensitivity: ignore
